import * as WH from "./wh";
import { Filter, Listview } from "./wh";

//<![CDATA[
WH.Gatherer.addData(3, 8, {
  "45912": {
    name_enus: "Book of Glyph Mastery",
    quality: 2,
    icon: "inv_misc_book_07",
    screenshot: {},
    jsonequip: { reqskill: 773, reqskillrank: 425, sellprice: 50000 },
    attainable: 0,
    flags2: 24576,
  },
  "50166": {
    name_enus: "Technique: Glyph of Eternal Water",
    quality: 1,
    icon: "inv_scroll_03",
    screenshot: {},
    jsonequip: {
      avgbuyout: 26783,
      buyprice: 30000,
      reqskill: 773,
      reqskillrank: 250,
      sellprice: 7500,
    },
    attainable: 0,
    flags2: 24576,
  },
  "50168": {
    name_enus: "Technique: Glyph of Quick Decay",
    quality: 1,
    icon: "inv_scroll_03",
    screenshot: {},
    jsonequip: {
      buyprice: 80000,
      reqskill: 773,
      reqskillrank: 375,
      sellprice: 20000,
    },
    attainable: 0,
    flags2: 24576,
  },
  "46108": {
    name_enus: "Technique: Rituals of the New Moon",
    quality: 2,
    icon: "inv_misc_book_07",
    screenshot: {},
    jsonequip: { reqskill: 773, reqskillrank: 350, sellprice: 20000 },
    attainable: 0,
    flags2: 24576,
  },
  "50167": {
    name_enus: "Technique: Glyph of Rapid Rejuvenation",
    quality: 1,
    icon: "inv_scroll_03",
    screenshot: {},
    jsonequip: {
      buyprice: 80000,
      reqskill: 773,
      reqskillrank: 375,
      sellprice: 20000,
    },
    attainable: 0,
    flags2: 24576,
  },
});
var listviewitems = [
  {
    classs: 9,
    flags2: 24576,
    id: 45912,
    level: 80,
    name: "Book of Glyph Mastery",
    quality: 2,
    skill: 425,
    slot: 0,
    source: [2],
    subclass: 11,
    firstseenpatch: 0,
    popularity: 513,
  },
  {
    classs: 9,
    flags2: 24576,
    id: 46108,
    level: 70,
    name: "Technique: Rituals of the New Moon",
    quality: 2,
    skill: 350,
    slot: 0,
    subclass: 11,
    firstseenpatch: 0,
    popularity: 78,
  },
  {
    classs: 9,
    flags2: 24576,
    id: 50166,
    level: 50,
    name: "Technique: Glyph of Eternal Water",
    quality: 1,
    skill: 250,
    slot: 0,
    source: [5],
    subclass: 11,
    firstseenpatch: 0,
    popularity: 171,
  },
  {
    classs: 9,
    flags2: 24576,
    id: 50167,
    level: 70,
    name: "Technique: Glyph of Rapid Rejuvenation",
    quality: 1,
    skill: 375,
    slot: 0,
    source: [5],
    sourcemore: [{ n: "Larana Drome", t: 1, ti: 28723, z: 4395 }],
    subclass: 11,
    firstseenpatch: 0,
    popularity: 53,
  },
  {
    classs: 9,
    flags2: 24576,
    id: 50168,
    level: 70,
    name: "Technique: Glyph of Quick Decay",
    quality: 1,
    skill: 375,
    slot: 0,
    source: [5],
    sourcemore: [{ n: "Larana Drome", t: 1, ti: 28723, z: 4395 }],
    subclass: 11,
    firstseenpatch: 0,
    popularity: 153,
  },
];
new Listview({
  template: "item",
  id: "items",
  extraCols: ["contentPhase"].concat(["popularity"]),
  sort: ["popularity"],
  maxPopularity: 513,
  onAfterCreate: Filter.listview_addUpgradeIndicator,
  visibleCols: ["skill"],
  hiddenCols: ["type", "slot"],
  customFilter: WH.Page.Items.parentItemFilter,
  data: listviewitems,
});
//]]>

export const recipes = WH.Gatherer.items;
